name: Cypress PoC (Tag-Based)

on:
  workflow_dispatch:

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 🧩 Rodando Cypress com reporter Mochawesome
      - name: Run Cypress tests with Mochawesome
        id: cypress
        continue-on-error: true  # garante que mesmo falhando siga o fluxo
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: npx cypress run --env grep=@smoke --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=true,html=true,json=true

      # 🧩 Faz merge dos JSONs e gera HTML final
      - name: Merge Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json
          npx marge cypress/reports/report.json --reportDir cypress/reports --inline

      # 🧩 Upload do relatório sempre, mesmo se falhar
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      # 🧩 Upload dos screenshots apenas se falhar
      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 🧩 Upload dos vídeos (sempre)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
